---
:keywords:
- :type: :url
  :url: http://amazon.com/exec/obidos/search-handle-url/index=books&field-keywords=%Q%
  :keywords:
  - book
  - books
- :type: :url
  :url: http://maps.google.com/maps?q=%Q%
  :keywords:
  - map
  - gmap
- :type: :password
  :keywords:
  - pass
